export const DUMMY_ACTION = 'DUMMY_ACTION';

export const MOVIE_ACTION = {
  ON_SEARCH_MOVIES: 'ON_SEARCH_MOVIES',
  GET_SEARCH_MOVIES: 'GET_SEARCH_MOVIES',
};

export const MOVIE_DB = {
  BASE_URI: 'http://api.themoviedb.org/3',
  IMAGES_URI: 'http://image.tmdb.org/t/p',
  AUTH_KEY_V3: '7d9a2fbb6e0bcd8c1bc350f6fe6d4057',
  AUTH_KEY_V4: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZDlhMmZiYjZlMGJjZDhjMWJjMzUwZjZmZTZkNDA1NyIsInN1YiI6IjVhNTM5N2U1MGUwYTI2MDI2MDAzNzhkOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WBDJ3ewZrcnFO-P1GCUg_gkoRZP70f-YqRsTUOq5q84',
};
